### ISSUE TITLE
출석 테이블!

### ISSUE THREAD

**Issue by Burningsweetpotato** [TalentDonationChallenge/BreatheGym#3]
출석 테이블엔 회원들이 이제껏 출결한 기록을 남겨야 하는거...죠?

그러면 barcode 에 primary key를 빼던가 (barcode,data) 둘다 함께 묶어서 primary key를 만들어야 할 것 같은뎅

barcode만 primary key로 해 놓으니 이전 기록들이 저장이 안돼요...

**Comment by lovelyhwado** [comment]
고치세여 ㅇㅅㅇ... data? 가 아니라 날짜+시간 인듯?

**Comment by Burningsweetpotato** [comment]
뉑 알겠습니다
