### ISSUE TITLE
버그리포팅?

### ISSUE THREAD

**Issue by heojae91** [TalentDonationChallenge/BreatheGym#4]
![2015-08-02 3 39 45](https://cloud.githubusercontent.com/assets/10989251/9027909/d5898056-392c-11e5-81c3-412f27110bab.png)
운동메뉴 추가할때 세트 수로 입력하게 되면 count가 입력되어야하는데 디비에는 null이 입력됩니다

그리고 운동메뉴 추가할때 이름 똑같은게 막 들어가니까 헷갈릴수도 있을거같아여

**Comment by lovelyhwado** [comment]
알았다 수정하게따
그러나 더 찾아내도록하여라

**Comment by lovelyhwado** [comment]
이거슨 이제 쓸모없게되어따
